feat(CI): Enhance lint checks to compare count from PR and main branch
PiperOrigin-RevId: 734302565

diff --git a/.github/workflows/format.yml b/.github/workflows/format.yml
--- a/.github/workflows/format.yml
+++ b/.github/workflows/format.yml
@@ -13,7 +13,7 @@ jobs:
 
     strategy:
       matrix:
-        node-version: [22.x]
+        node-version: [18.x, 20.x, 22.x]
 
     steps:
     - uses: actions/checkout@v4
@@ -30,10 +30,42 @@ jobs:
       run: |
         echo "Formatting failed. To resolve this issue, please run `npm run format` on your change."
         exit 1
-    - name: Run linting
-      run: npm run lint
+    - name: Get PR lint count
+      id: pr-lint-count
+      run: |
+        PR_LINT_COUNT=$(npm run lint | tail -n 2 | head -n 1 | awk '{print $2 + 0}')
+        echo "pr_count=$PR_LINT_COUNT" >> $GITHUB_OUTPUT
     - name: Check lint result
       if: ${{ failure() }}
       run: |
         echo "Linting failed. To resolve this issue, please run `npm run lint-fix` on your change."
         exit 1
+    - name: Checkout Main Branch
+      uses: actions/checkout@v4
+      with:
+        ref: main
+    - name: Use Node.js ${{ matrix.node-version }}
+      uses: actions/setup-node@v4
+      with:
+        node-version: ${{ matrix.node-version }}
+        cache: 'npm'
+    - run: npm ci
+    - name: Get main lint count
+      id: main-lint-count
+      run: |
+        MAIN_LINT_COUNT=$(npm run lint | tail -n 2 | head -n 1 | awk '{print $2 + 0}')
+        echo "main_count=$MAIN_LINT_COUNT" >> $GITHUB_OUTPUT
+    - name: Compare Lint Counts
+      run: |
+        PR_COUNT=${{ steps.pr-lint-count.outputs.pr_count }}
+        MAIN_COUNT=${{ steps.main-lint-count.outputs.main_count }}
+
+        echo "PR Lint Count: $PR_COUNT"
+        echo "Main Lint Count: $MAIN_COUNT"
+
+        if [[ "$PR_COUNT" -gt "$MAIN_COUNT" ]]; then
+          echo "Error: PR lint count ($PR_COUNT) is greater than main branch lint count ($MAIN_COUNT)"
+          exit 1
+        else
+          echo "PR lint count is not greater than main branch lint count.  Success!"
+        fi
